"""Roll every committed scorecard up into `results/REFRESHED.md`.

Phase 4: *"Results last refreshed on <date> with <versions>"*. Each
`results/<arena>/scorecard.json` already carries its own run date, model and the
adapter versions it used; this collects them into one table so a reader can see
how stale the published numbers are without opening every arena's file.

`results/` is live-only and currently empty, so this ships as a placeholder that
fills in the first time `full-run` writes a scorecard.
"""

from __future__ import annotations

import json
from pathlib import Path

from .scorecard import RESULTS_DIR

_MARKER = "<!-- generated by `python -m arena refreshed` - do not edit by hand -->"


def _scorecards(root: Path):
    for jf in sorted(root.glob("*/scorecard.json")):
        try:
            yield json.loads(jf.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue


def render(root: Path = RESULTS_DIR) -> str:
    cards = list(_scorecards(root))
    lines = [_MARKER, "", "# Results - last refreshed", ""]
    if not cards:
        lines += [
            "_No live scorecard has been published yet._ Once the `full-run` workflow",
            "writes one into `results/`, this table fills in automatically - run",
            "`python -m arena refreshed` (or just `arena scorecard --mode live`).",
            "",
        ]
        return "\n".join(lines)

    lines += [
        "| Arena | Last run (UTC) | Model | Harness | Adapter versions |",
        "|---|---|---|---|---|",
    ]
    newest = ""
    for card in cards:
        meta = card["meta"]
        avail = [r for r in card["rows"] if r.get("available")]
        versions = ", ".join(f"{r['framework']} {r['lib_version']}" for r in avail) or "-"
        started = meta.get("started_at", "?")
        newest = max(newest, started)
        lines.append(
            f"| `{meta['arena']}` | {started} | {meta.get('model', '?')} | "
            f"v{meta.get('harness_version', '?')} | {versions} |"
        )
    lines += ["", f"Most recent run: **{newest}**.", ""]
    return "\n".join(lines)


def write_index(root: Path = RESULTS_DIR) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    out = root / "REFRESHED.md"
    # Always LF: this file is committed and CI diffs it, so a CRLF write on a
    # Windows dev box must not show up as drift against a Linux runner.
    out.write_text(render(root) + "\n", encoding="utf-8", newline="\n")
    return out
