"""Turns a run record into committed scorecards (markdown + json + csv)."""

from __future__ import annotations

import csv
import io
import json
from pathlib import Path
from typing import Any

from .config import REPO_ROOT

RESULTS_DIR = REPO_ROOT / "results"
RUNS_DIR = REPO_ROOT / "runs"


def latest_run(arena_id: str, mode: str | None = None) -> dict[str, Any]:
    candidates = sorted(RUNS_DIR.glob(f"*__{arena_id}__*.json"))
    if mode:
        candidates = [p for p in candidates if p.stem.endswith(f"__{mode}")]
    if not candidates:
        raise FileNotFoundError(f"no runs found for arena {arena_id!r} in {RUNS_DIR}")
    return json.loads(candidates[-1].read_text(encoding="utf-8"))


def _aggregate(record: dict[str, Any]) -> list[dict[str, Any]]:
    price_in = record["pricing"]["input_per_m"]
    price_out = record["pricing"]["output_per_m"]
    rows: list[dict[str, Any]] = []
    for fw in record["frameworks"]:
        if not fw.get("available", False):
            rows.append(
                {
                    "framework": fw["framework"],
                    "available": False,
                    "reason": fw.get("reason", "unavailable"),
                }
            )
            continue
        items = fw["items"]
        n = len(items) or 1
        passed = sum(1 for it in items if it["passed"])
        errors = sum(1 for it in items if it["error"])
        pt = sum(it["prompt_tokens"] for it in items)
        ct = sum(it["completion_tokens"] for it in items)
        latency = sum(it["latency_s"] for it in items)
        llm_calls = sum(it["llm_calls"] for it in items)
        rows.append(
            {
                "framework": fw["framework"],
                "available": True,
                "lib_version": fw.get("lib_version", "?"),
                "items": len(items),
                "pass_rate": round(passed / n, 3),
                "passed": passed,
                "errors": errors,
                "mean_latency_s": round(latency / n, 3),
                "total_tokens": pt + ct,
                "mean_tokens": round((pt + ct) / n, 1),
                "mean_llm_calls": round(llm_calls / n, 2),
                "est_cost_usd": round(pt / 1e6 * price_in + ct / 1e6 * price_out, 6),
            }
        )
    rows.sort(key=lambda r: (not r["available"], -(r.get("pass_rate") or 0)))
    return rows


def _render_markdown(record: dict[str, Any], rows: list[dict[str, Any]]) -> str:
    lines = [
        f"# Scorecard — `{record['arena']}`",
        "",
        f"> {record['arena_description']}",
        "",
        f"- **Mode:** {record['mode']}"
        + ("  ⚠️ plumbing only — not a quality signal" if record["mode"] == "mock" else ""),
        f"- **Model:** {record['model']}",
        f"- **Dataset:** {record['dataset_size']} items × {record['repeat']} repeat(s)",
        f"- **Run at:** {record['started_at']} ({record['duration_s']}s)",
        f"- **Harness:** v{record['harness_version']} · Python {record['python']}",
        "",
        "| Framework | Ver | Pass rate | Errors | Mean latency | Mean tokens | Mean LLM calls | Est. cost |",
        "|---|---|--:|--:|--:|--:|--:|--:|",
    ]
    for r in rows:
        if not r["available"]:
            lines.append(f"| `{r['framework']}` | — | _not available_ | — | — | — | — | — |")
            continue
        lines.append(
            f"| `{r['framework']}` | {r['lib_version']} | "
            f"{r['pass_rate']:.0%} ({r['passed']}/{r['items']}) | {r['errors']} | "
            f"{r['mean_latency_s']:.3f}s | {r['mean_tokens']:.0f} | {r['mean_llm_calls']:.2f} | "
            f"${r['est_cost_usd']:.4f} |"
        )
    unavailable = [r for r in rows if not r["available"]]
    if unavailable:
        lines += ["", "**Not available this run:**", ""]
        lines += [f"- `{r['framework']}` — {r['reason']}" for r in unavailable]
    lines += [
        "",
        "_Generated by `python -m arena scorecard`. Do not edit by hand._",
        "",
    ]
    return "\n".join(lines)


def _render_csv(rows: list[dict[str, Any]]) -> str:
    buf = io.StringIO()
    fields = [
        "framework",
        "available",
        "lib_version",
        "items",
        "pass_rate",
        "errors",
        "mean_latency_s",
        "total_tokens",
        "mean_tokens",
        "mean_llm_calls",
        "est_cost_usd",
        "reason",
    ]
    writer = csv.DictWriter(buf, fieldnames=fields, extrasaction="ignore")
    writer.writeheader()
    for r in rows:
        writer.writerow(r)
    return buf.getvalue()


def write_scorecard(record: dict[str, Any]) -> Path:
    rows = _aggregate(record)
    out_dir = RESULTS_DIR / record["arena"]
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "scorecard.md").write_text(_render_markdown(record, rows), encoding="utf-8")
    (out_dir / "scorecard.csv").write_text(_render_csv(rows), encoding="utf-8")
    (out_dir / "scorecard.json").write_text(
        json.dumps(
            {"meta": {k: v for k, v in record.items() if k != "frameworks"}, "rows": rows}, indent=2
        ),
        encoding="utf-8",
    )
    return out_dir / "scorecard.md"
